name: Runs with error
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # service/sidecar container for azure-sql-edge
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:latest
        env:
          ACCEPT_EULA: 1
          SA_PASSWORD: P@ssw0rd
        ports:
          - 1433:1433

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'wait for sql server to be ready'
        run: |
          set +o pipefail +e
          for i in {1..60};
          do
              sqlcmd -S localhost -U sa -P P@ssw0rd -d master -Q "select getdate()"
              if [ $? -eq 0 ]
              then
                  echo "sql server ready"
                  break
              else
                  echo "not ready yet..."
                  sleep 1
              fi
          done
          set -o pipefail -e

      - name: run query plan query
        run: |
          sqlcmd -S localhost -U sa -P P@ssw0rd -d master -y 0 -i ./sample-github-workflows/get-row.sql -o output.txt
      
      - name: 'parsing output.txt for number of rows affected'
        id: row_count
        run: |
          echo "::set-output name=rows::$(grep ' affected)' output.txt)"
      
      - name: 'output summary on multiple rows'
        if : steps.row_count.outputs.rows != '(0 rows affected)'
        run: |
          echo "### :rotating_light: Index issue found" >> $GITHUB_STEP_SUMMARY # adds the run summary
          echo "$(cat output.txt)" >> $GITHUB_STEP_SUMMARY
          echo "::error title=Index Issue Found::Check the output for more details" # adds the annotation
          exit 1 # exits the workflow with an error code

      - name: 'output summary on 0 rows'
        if: steps.row_count.outputs.rows == '(0 rows affected)'
        run: |
          echo "### :white_check_mark: No issues found" >> $GITHUB_STEP_SUMMARY